// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using web2.ef;

#nullable disable

namespace web2.Migrations
{
    [DbContext(typeof(Mydbcontext))]
    [Migration("20230727040055_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("web2.ef.boy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("allmoney")
                        .HasColumnType("INTEGER");

                    b.Property<int>("n")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("stepId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("stepId");

                    b.ToTable("boy", (string)null);
                });

            modelBuilder.Entity("web2.ef.ord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("cusid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("cusna")
                        .HasColumnType("TEXT");

                    b.Property<int>("dend")
                        .HasColumnType("INTEGER");

                    b.Property<string>("des")
                        .HasColumnType("TEXT");

                    b.Property<int>("dstar")
                        .HasColumnType("INTEGER");

                    b.Property<int>("first")
                        .HasColumnType("INTEGER");

                    b.Property<int>("isdel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("isend")
                        .HasColumnType("INTEGER");

                    b.Property<int>("n")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ordid")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ord", (string)null);
                });

            modelBuilder.Entity("web2.ef.step", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("dend")
                        .HasColumnType("INTEGER");

                    b.Property<int>("dstar")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isend")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isstar")
                        .HasColumnType("INTEGER");

                    b.Property<int>("month")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ordId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ordId");

                    b.ToTable("step", (string)null);
                });

            modelBuilder.Entity("web2.ef.boy", b =>
                {
                    b.HasOne("web2.ef.step", null)
                        .WithMany("iboy")
                        .HasForeignKey("stepId");
                });

            modelBuilder.Entity("web2.ef.step", b =>
                {
                    b.HasOne("web2.ef.ord", null)
                        .WithMany("istep")
                        .HasForeignKey("ordId");
                });

            modelBuilder.Entity("web2.ef.ord", b =>
                {
                    b.Navigation("istep");
                });

            modelBuilder.Entity("web2.ef.step", b =>
                {
                    b.Navigation("iboy");
                });
#pragma warning restore 612, 618
        }
    }
}
