// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using web2.ef;

#nullable disable

namespace web2.Migrations
{
    [DbContext(typeof(Mydbcontext))]
    [Migration("20230708032305_ini")]
    partial class ini
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("web2.ef.ord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("dte")
                        .HasColumnType("TEXT");

                    b.Property<int>("myid")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ord", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
